# Generated by Django 5.2.17 on 2026-09-11 19:55

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileSyncBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_id', models.CharField(max_length=128)),
                ('payload_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('completed', 'Completed')], default='completed', max_length=16)),
                ('counts', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='mobile_local_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='debt',
            name='mobile_local_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='installment',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='installment',
            name='mobile_local_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='installment',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='payment',
            name='mobile_local_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='payment',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(max_length=128, unique=True)),
                ('label', models.CharField(blank=True, max_length=160)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_synced_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='mobile_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='ledger.mobiledevice'),
        ),
        migrations.AddField(
            model_name='debt',
            name='mobile_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts', to='ledger.mobiledevice'),
        ),
        migrations.AddField(
            model_name='installment',
            name='mobile_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installments', to='ledger.mobiledevice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='mobile_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='ledger.mobiledevice'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('mobile_device', 'mobile_local_id'), name='unique_mobile_client_local_id'),
        ),
        migrations.AddConstraint(
            model_name='debt',
            constraint=models.UniqueConstraint(fields=('mobile_device', 'mobile_local_id'), name='unique_mobile_debt_local_id'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.UniqueConstraint(fields=('mobile_device', 'mobile_local_id'), name='unique_mobile_installment_local_id'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('mobile_device', 'mobile_local_id'), name='unique_mobile_payment_local_id'),
        ),
        migrations.AddField(
            model_name='mobilesyncbatch',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_batches', to='ledger.mobiledevice'),
        ),
        migrations.AddConstraint(
            model_name='mobilesyncbatch',
            constraint=models.UniqueConstraint(fields=('device', 'batch_id'), name='unique_mobile_device_batch'),
        ),
    ]
