# Generated by Django 5.2.17 on 2026-09-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_webpushsubscription_pushdelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='share_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
