# Generated by Django 5.2.17 on 2026-10-04 05:51

from django.db import migrations, models


def seed_reference_sequence(apps, schema_editor):
    Debt = apps.get_model('ledger', 'Debt')
    Sequence = apps.get_model('ledger', 'DebtReferenceSequence')
    numbers = (
        int(reference[4:]) for reference in Debt.objects.values_list('reference', flat=True)
        if reference.startswith('PNG-') and reference[4:].isdigit()
    )
    Sequence.objects.create(name='PNG', last_number=max(numbers, default=1000))


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_corporate_accounts_and_fiscal_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtReferenceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='PNG', max_length=16, unique=True)),
                ('last_number', models.PositiveIntegerField(default=1000)),
            ],
        ),
        migrations.RunPython(seed_reference_sequence, migrations.RunPython.noop),
    ]
