# Generated by Django 5.2.17 on 2026-10-04 06:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_debt_reference_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='revision',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='debt',
            name='revision',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='installment',
            name='revision',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='revision',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.CreateModel(
            name='SyncCursorFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.BigIntegerField(default=0)),
                ('organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.organization')),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SyncMutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mutation_id', models.UUIDField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('action', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(max_length=10)),
                ('result', models.JSONField(default=dict)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_mutations', to='ledger.mobiledevice')),
            ],
        ),
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.CharField(max_length=12)),
                ('entity_id', models.UUIDField()),
                ('reason', models.CharField(max_length=40)),
                ('client_payload', models.JSONField()),
                ('server_row', models.JSONField(default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='ledger.syncmutation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SyncChange',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity', models.CharField(max_length=12)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('op', models.CharField(max_length=8)),
                ('fields', models.JSONField(default=dict)),
                ('changed_fields', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.organization')),
                ('origin_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.mobiledevice')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mutation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.syncmutation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='syncmutation',
            constraint=models.UniqueConstraint(fields=('device', 'mutation_id'), name='unique_device_mutation'),
        ),
        migrations.AddIndex(
            model_name='syncchange',
            index=models.Index(fields=['owner', 'id'], name='ledger_sync_owner_i_c52d61_idx'),
        ),
        migrations.AddIndex(
            model_name='syncchange',
            index=models.Index(fields=['organization', 'id'], name='ledger_sync_organiz_92fa73_idx'),
        ),
    ]
