# Generated by Django 5.2.17 on 2026-10-09 13:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_backfill_sync_changes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='alt_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='client',
            name='bank_accounts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='client',
            name='contacts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='client',
            name='country_of_birth',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='client',
            name='id_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='client',
            name='nuit',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.CreateModel(
            name='AmortizationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_type', models.CharField(choices=[('multi', 'Multi-period'), ('single', 'Single loan')], max_length=8)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('duration_months', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('schedule_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortization_plans', to='ledger.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortization_plans', to='ledger.organization')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
