# Generated by Django 5.2.17 on 2026-10-09 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_client_details_and_amortization_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='amortizationplan',
            name='debt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amortization_plans', to='ledger.debt'),
        ),
        migrations.AddField(
            model_name='amortizationplan',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
