from django.urls import path

from . import views
from . import sync_v2_views

urlpatterns = [
    path("sync/v2/config/", sync_v2_views.config_view),
    path("sync/v2/hello/", sync_v2_views.hello_view),
    path("sync/v2/changes/", sync_v2_views.changes_view),
    path("sync/v2/push/", sync_v2_views.push_view),
    path("sync/v2/bootstrap/", sync_v2_views.bootstrap_view),
    path("bootstrap/", views.bootstrap_view),
    path("dashboard/summary/", views.dashboard_summary_view),
    path("dashboard/debts/", views.dashboard_debts_view),
    path("auth/csrf/", views.csrf),
    path("auth/login/", views.login_view),
    path("auth/register/", views.register_view),
    path("auth/logout/", views.logout_view),
    path("auth/password-reset/", views.password_reset_request_view),
    path("auth/password-reset/confirm/", views.password_reset_confirm_view),
    path("mobile/register/", views.mobile_register_view),
    path("mobile/login/", views.mobile_login_view),
    path("mobile/sync/", views.mobile_sync_view),
    path("push/config/", views.push_config_view),
    path("push/subscription/", views.push_subscription_view),
    path("push/test/", views.push_test_view),
    path("auth/me/", views.me_view),
    path("preferences/", views.preferences_view),
    path("clients/", views.clients_view),
    path("clients/<int:client_id>/", views.client_detail_view),
    path("clients/<int:client_id>/share/", views.client_share_view),
    path("clients/by-public-id/<uuid:public_id>/share/", views.client_share_by_public_id_view),
    path("public/clients/<str:token>/", views.public_client_view),
    path("debts/", views.debts_view),
    path("debts/<str:reference>/", views.debt_detail_view),
    path("debts/<str:reference>/payments/", views.debt_payment_view),
    path("debts/<str:reference>/installments/<int:number>/revert/", views.installment_revert_view),
    path("payments/", views.payments_view),
    path("organizations/staff/", views.staff_list_view),
    path("organizations/staff/<int:user_id>/", views.staff_detail_view),
    path("organizations/documents/<str:document_type>/", views.document_list_view),
    path("organizations/documents/schedule/<str:reference>/", views.amortization_schedule_view),
]
